<?php
/**
 * ShadowORM Database Drop-In
 *
 * This file is auto-generated by ShadowORM plugin.
 * Do not edit manually - changes will be overwritten.
 *
 * @package ShadowORM
 */

if (!defined('ABSPATH')) {
    exit;
}

// Mark that ShadowORM db.php is loaded
if (!defined('SHADOW_ORM_DB_LOADED')) {
    define('SHADOW_ORM_DB_LOADED', true);
}

// Load the original wpdb
require_once ABSPATH . WPINC . '/wp-db.php';

// Initialize wpdb
if (!isset($GLOBALS['wpdb'])) {
    $GLOBALS['wpdb'] = new wpdb(DB_USER, DB_PASSWORD, DB_NAME, DB_HOST);
}

// ShadowORM hooks will be registered later by the plugin itself
// This drop-in only marks that ShadowORM is active
